spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jameaamo@gmail.com
    password: oxnnzotqnxmcqcqr
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/userauth
    username: postgres
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8099